apiVersion: v1
kind: Pod
metadata:
  name: multipod
spec:
  volumes:
  - name: shared-data
    emptyDir: {}
  containers:
  - name: web-nginx
    image: nginx
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
  - name: ftp-container
    image: fauria/vsftpd
    volumeMounts:
    - name: shared-data
      mountPath: /pod-data  
    env:
    - name: FTP_ADMIN
      value: admin
    - name: FTP_PASS
      value: password
