apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-multi-path
  labels:
    app: frontend
    env: dev
spec:
  replicas: 3
  selector:
    matchLabels:
       app: frontend
       env: dev
  template:
    metadata:
      name: webapp-multi-path
      labels:
        app: frontend
        env: dev
    spec:
      containers:
      - name: webapp
        image: gcr.io/playground-s-11-b3468c19/pythonapp:latest
        ports:
        - containerPort: 8888